(function() {var implementors = {};
implementors["bikeshare"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Api.html\" title=\"struct bikeshare::types::Api\">Api</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a>,&nbsp;</span>",synthetic:true,types:["bikeshare::types::Api"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"bikeshare/types/struct.ApiData.html\" title=\"struct bikeshare::types::ApiData\">ApiData</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a>,&nbsp;</span>",synthetic:true,types:["bikeshare::types::ApiData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Status.html\" title=\"struct bikeshare::types::Status\">Status</a>",synthetic:true,types:["bikeshare::types::Status"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Information.html\" title=\"struct bikeshare::types::Information\">Information</a>",synthetic:true,types:["bikeshare::types::Information"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStation.html\" title=\"struct bikeshare::types::JoinedStation\">JoinedStation</a>",synthetic:true,types:["bikeshare::types::JoinedStation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStatus.html\" title=\"struct bikeshare::types::JoinedStatus\">JoinedStatus</a>",synthetic:true,types:["bikeshare::types::JoinedStatus"]},];
implementors["sykl"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sykl/struct.Void.html\" title=\"struct sykl::Void\">Void</a>",synthetic:true,types:["sykl::Void"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Unpin.html\" title=\"trait core::marker::Unpin\">Unpin</a> for <a class=\"struct\" href=\"sykl/formatting/struct.Row.html\" title=\"struct sykl::formatting::Row\">Row</a>&lt;'a&gt;",synthetic:true,types:["sykl::formatting::Row"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()