(function() {var implementors = {};
implementors["bikeshare"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Api.html\" title=\"struct bikeshare::types::Api\">Api</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a>,&nbsp;</span>",synthetic:true,types:["bikeshare::types::Api"]},{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"bikeshare/types/struct.ApiData.html\" title=\"struct bikeshare::types::ApiData\">ApiData</a>&lt;T&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;T: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a>,&nbsp;</span>",synthetic:true,types:["bikeshare::types::ApiData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Status.html\" title=\"struct bikeshare::types::Status\">Status</a>",synthetic:true,types:["bikeshare::types::Status"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Information.html\" title=\"struct bikeshare::types::Information\">Information</a>",synthetic:true,types:["bikeshare::types::Information"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStation.html\" title=\"struct bikeshare::types::JoinedStation\">JoinedStation</a>",synthetic:true,types:["bikeshare::types::JoinedStation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStatus.html\" title=\"struct bikeshare::types::JoinedStatus\">JoinedStatus</a>",synthetic:true,types:["bikeshare::types::JoinedStatus"]},];
implementors["sykl"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"sykl/struct.Void.html\" title=\"struct sykl::Void\">Void</a>",synthetic:true,types:["sykl::Void"]},];
implementors["sykl_formatting"] = [{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"sykl_formatting/struct.Row.html\" title=\"struct sykl_formatting::Row\">Row</a>&lt;'a&gt;",synthetic:true,types:["sykl_formatting::Row"]},];
implementors["sykl_rest"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"sykl_rest/struct.station.html\" title=\"struct sykl_rest::station\">station</a>",synthetic:true,types:["sykl_rest::station"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"struct\" href=\"sykl_rest/struct.all_stations.html\" title=\"struct sykl_rest::all_stations\">all_stations</a>",synthetic:true,types:["sykl_rest::all_stations"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> for <a class=\"enum\" href=\"sykl_rest/enum.InternalError.html\" title=\"enum sykl_rest::InternalError\">InternalError</a>",synthetic:true,types:["sykl_rest::InternalError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()