(function() {var implementors = {};
implementors["bikeshare"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"bikeshare/types/struct.Status.html\" title=\"struct bikeshare::types::Status\">Status</a>&gt; for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStatus.html\" title=\"struct bikeshare::types::JoinedStatus\">JoinedStatus</a>",synthetic:false,types:["bikeshare::types::JoinedStatus"]},{text:"impl&lt;'_&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;&amp;'_ <a class=\"struct\" href=\"bikeshare/types/struct.Status.html\" title=\"struct bikeshare::types::Status\">Status</a>&gt; for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStatus.html\" title=\"struct bikeshare::types::JoinedStatus\">JoinedStatus</a>",synthetic:false,types:["bikeshare::types::JoinedStatus"]},];
implementors["sykl_rest"] = [{text:"impl&lt;T&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/sys_common/poison/struct.PoisonError.html\" title=\"struct std::sys_common::poison::PoisonError\">PoisonError</a>&lt;T&gt;&gt; for <a class=\"enum\" href=\"sykl_rest/enum.InternalError.html\" title=\"enum sykl_rest::InternalError\">InternalError</a>",synthetic:false,types:["sykl_rest::InternalError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()