(function() {var implementors = {};
implementors["bikeshare"] = [{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Api.html\" title=\"struct bikeshare::types::Api\">Api</a>&lt;T&gt;",synthetic:false,types:["bikeshare::types::Api"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"bikeshare/types/struct.ApiData.html\" title=\"struct bikeshare::types::ApiData\">ApiData</a>&lt;T&gt;",synthetic:false,types:["bikeshare::types::ApiData"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Status.html\" title=\"struct bikeshare::types::Status\">Status</a>",synthetic:false,types:["bikeshare::types::Status"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"bikeshare/types/struct.Information.html\" title=\"struct bikeshare::types::Information\">Information</a>",synthetic:false,types:["bikeshare::types::Information"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStation.html\" title=\"struct bikeshare::types::JoinedStation\">JoinedStation</a>",synthetic:false,types:["bikeshare::types::JoinedStation"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"struct\" href=\"bikeshare/types/struct.JoinedStatus.html\" title=\"struct bikeshare::types::JoinedStatus\">JoinedStatus</a>",synthetic:false,types:["bikeshare::types::JoinedStatus"]},];
implementors["sykl_rest"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/fmt/trait.Debug.html\" title=\"trait core::fmt::Debug\">Debug</a> for <a class=\"enum\" href=\"sykl_rest/enum.InternalError.html\" title=\"enum sykl_rest::InternalError\">InternalError</a>",synthetic:false,types:["sykl_rest::InternalError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()